tasks:
        - deepsea.preflight:
        - deepsea.orch:
                stage: prep
        - deepsea.orch:
                stage: 1
        - deepsea.policy:
                profile: default
        - deepsea.orch:
                stage: 2
        - deepsea.ceph_conf:
        - deepsea.orch:
                stage: 3
        - deepsea.create_pools:
                openstack: 
        - deepsea.orch:
                stage: 4
        - exec:
                client.salt_master:
                        - 'ceph -s'
        - workunit:
                clients:
                        client.salt_master:
                                - build_validation/other_test_cases/convert_repl_to_ec_pool.sh
